import { GMap } from '@/components/GMap';
import { Header } from '@/components/Header';
import type { VendingType } from '@/lib/@type/vending';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
interface HomeProps {
  contents: VendingType[]
}
const Home:NextPage<HomeProps> = ({contents}) => {
  console.log(contents);
  
  return (
    <>
      <Head>
        <title>自販機君</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <GMap contents={contents}/>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps<HomeProps> = async () => {

  try {
    
    // ここでAPIからデータを取得する例（実際のAPIエンドポイントに合わせて変更してください）
    // const response = await fetch('/api/get-vending-machine');
    const response = await fetch('http://localhost:3000/api/get-vending-machine');
    const {contents} = await response.json();
  
    return {
      props: {
        contents,
      },
    };
  } catch (error) {
    console.log(error);
    
    return {
      props: {
        contents: [],
      },
    };
  }
};

export default Home;